name: OID check

on:
  push:
    branches: [ data ]
  pull_request:
    branches: [ data ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Check the OIDs
      run: |
        python .github/workflows/oids.py
